version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: .docker/api/Dockerfile
    ports:
      - 3333:3333
    volumes:
      - ./api:/go/src/github.com/blyndusk/repo-template/api
    networks:
      - main
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - main
volumes:
  elasticsearch:

networks:
  main:
